### ISSUE TITLE
[server] delete all focusのエラー

### ISSUE THREAD

**Issue by mahiro72** [jphacks/F_2205#95]
### 内容

https://console.cloud.google.com/logs/query;query=resource.type%20%3D%20%22cloud_run_revision%22%0Aresource.labels.service_name%20%3D%20%22f-2205-server%22%0Aresource.labels.location%20%3D%20%22asia-east1%22%0A%20severity%3E%3DDEFAULT;timeRange=2022-10-21T12:25:00.670130Z%2F2022-10-21T12:25:00.670130Z--PT1H;pinnedLogId=2022-10-21T12:25:00.670130Z%2F63528f9c000a39b2783a79d1?project=serious-timer-366017

### TODO
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by mahiro72** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 
addr=0x8 pc=0x6376d5] goroutine 64 [running]: github.com/jphacks/F_2205/server/src/infrastructure/persistance.
(*FocusRepository).DelAllFocus(0xc00039ceb0, {0xc000287190, 0x48}, {0xc0003bac60, 0x10}) 
/go/src/github.com/jphacks/F_2205/server/src/infrastructure/persistance/focus.go:128 +0x175 
github.com/jphacks/F_2205/server/src/usecase.(*FocusUseCase).DelAllFocus(0xc000157f88, {0xc000287190, 0xc00039ceb0}, 
{{0xc0003bac60, 0x0}, {0x0, 0x0}}) /go/src/github.com/jphacks/F_2205/server/src/usecase/focus.go:64 +0x5c 
github.com/jphacks/F_2205/server/src/web/handler.(*FocusHandler).readPump(0xc0003617b0, 0xc00040aa20) 
/go/src/github.com/jphacks/F_2205/server/src/web/handler/focus.go:81 +0x490 created by 
github.com/jphacks/F_2205/server/src/web/handler.(*FocusHandler).serveWs 
/go/src/github.com/jphacks/F_2205/server/src/web/handler/focus.go:137 +0x1fd
```

**Comment by mahiro72** [comment]
func (r *FocusRepository) DelAllFocusでエラー

**Comment by mahiro72** [comment]
おそらく、connectのリストにnullが入っている
